image: maven:3.6.0-jdk-11-slim

variables:
  MAVEN_OPTS: "-Dmaven.repo.local=$CI_PROJECT_DIR/.m2/repository"
  MAVEN_CLI_OPTS: "--batch-mode --show-version -P ci"

cache:
  paths:
    - .m2/repository
    - Planificateur/target/

‚öômaven-build:
  stage: build
  script:
    - cd Planificateur
    - mvn $MAVEN_CLI_OPTS compile

üß™junit-test:
  stage: test
  script:
    - cd Planificateur
    - mvn $MAVEN_CLI_OPTS -B test

üìñjavadoc:
  stage: deploy
  script:
    - cd Planificateur
    - mvn $MAVEN_CLI_OPTS -DskipTests=true -B javadoc:javadoc
  artifacts:
    paths:
      - Simulator/target/site/apidocs
    expire_in: 30 days

‚èØbuild-jar:
  stage: deploy
  script:
    - cd Planificateur
    - mvn $MAVEN_CLI_OPTS -DskipTests=true -B package
    - cp target/Scheduler.jar Scheduler.jar
  artifacts:
    paths:
      - Planificateur/Scheduler.jar
      - Planificateur/README.md
      - Planificateur/gyms.csv
      - Planificateur/teams.csv
    expire_in: 30 days
